import Head from "next/head";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <>
      <Head>
        <title>An's House | Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.intro}>
        <div className={styles.content}>
          <a className={styles.a1}>Hi! We are</a>
          <a className={styles.a2}>An's House</a>
          <a className={styles.a3}>
            Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do
            eiusmod tempor incididunt ut labore et dolore magna aliqua. Nisl
            tincidunt eget nullam non. Lorem ipsum dolor sit amet, consectetur
            adipiscing elit, sed do eiusmod tempor incididunt ut labore et
            dolore magna aliqua. Nisl tincidunt eget nullam non.
          </a>
        </div>
        <div className={styles.slice}>
          <img src="/slice.png" />
        </div>
      </div>
      <hr />
      <div className={styles.tab_bar}>
        <div className={styles.tab_item}>
          <div className={styles.nav_tab}>
            <div className={styles.tab}>Popular</div>
            <div className={styles.tab}>Newest </div>
            <div className={styles.tab}>Ratest </div>
            <div className={styles.tab}>All</div>
          </div>
          <div className={styles.btn_search}>
            <input placeholder="Search"></input>
            <img src="/iconSearch.png" />
          </div>
        </div>
        <div className={styles.content_post}>
          <div className={styles.post}>
            <h1>Heading Title's Post 1</h1>
            <h2>Desc posts</h2>
            <p>
              Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do
              eiusmod tempor incididunt ut labore et dolore magna aliqua. Nisl
              tincidunt eget nullam non Lorem ipsum dolor sit amet, consectetur
              adipiscing elit, sed do eiusmod.
            </p>
            <h2 className={styles.h}>
              Read full post{" "}
              <svg
                style={{ marginBottom: -5 }}
                xmlns="http://www.w3.org/2000/svg"
                width="24"
                height="24"
                fill="currentColor"
                class="bi bi-arrow-right-circle-fill"
                viewBox="0 0 16 16"
              >
                <path d="M8 0a8 8 0 1 1 0 16A8 8 0 0 1 8 0zM4.5 7.5a.5.5 0 0 0 0 1h5.793l-2.147 2.146a.5.5 0 0 0 .708.708l3-3a.5.5 0 0 0 0-.708l-3-3a.5.5 0 1 0-.708.708L10.293 7.5H4.5z" />
              </svg>
            </h2>
          </div>
          <img className={styles.postImage} src="/intro_content.png" />
        </div>
        <div className={styles.content_post}>
          <div className={styles.post}>
            <h1>Heading Title's Post 1</h1>
            <h3>Desc posts</h3>
            <p>
              Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do
              eiusmod tempor incididunt ut labore et dolore magna aliqua. Nisl
              tincidunt eget nullam non Lorem ipsum dolor sit amet, consectetur
              adipiscing elit, sed do eiusmod.
            </p>
            <h3 className={styles.h}>
              Read full post{" "}
              <svg
                style={{ marginBottom: -5 }}
                xmlns="http://www.w3.org/2000/svg"
                width="24"
                height="24"
                fill="currentColor"
                class="bi bi-arrow-right-circle-fill"
                viewBox="0 0 16 16"
              >
                <path d="M8 0a8 8 0 1 1 0 16A8 8 0 0 1 8 0zM4.5 7.5a.5.5 0 0 0 0 1h5.793l-2.147 2.146a.5.5 0 0 0 .708.708l3-3a.5.5 0 0 0 0-.708l-3-3a.5.5 0 1 0-.708.708L10.293 7.5H4.5z" />
              </svg>
            </h3>
          </div>
          <img className={styles.postImage} src="/intro_content.png" />
        </div>
      </div>
    </>
  );
}
